version: '3.8'

services:
  pulse-engine:
    build: .
    container_name: pulse-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./user_profile.json:/app/user_profile.json
    restart: unless-stopped
    
  # If someone wants to run Qdrant locally instead of the cloud, 
  # they can just uncomment the block below!
  # qdrant:
  #   image: qdrant/qdrant:latest
  #   ports:
  #     - "6333:6333"
  #   volumes:
  #     - ./qdrant_data:/qdrant/storage