# version: '3.8'

services:
  pulse-engine:
    build: .
    container_name: pulse-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    # depends_on:
    #   - postgres_db
    volumes:
      - ./user_profile.json:/app/user_profile.json
    restart: unless-stopped

# for people who would like to configure the postgres db on their local machine

  # postgres_db:
  #   image: postgres:15-alpine
  #   container_name: pulse-postgres
  #   environment:
  #     # In production, pull these values from a secure .env file, 
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: passwd123
  #     POSTGRES_DB: pulse_db
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pulse_pg_data:path
  #   restart: unless-stopped
    
  # If someone wants to run Qdrant locally instead of the cloud, 
  # they can just uncomment the block below!
  # qdrant:
  #   image: qdrant/qdrant:latest
  #   ports:
  #     - "6333:6333"
  #   volumes:
  #     - ./qdrant_data:/qdrant/storage

volumes:
  pulse_pg_data:
